# Use the official Node image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY ./server/package*.json ./

# Install NestJS dependencies
RUN npm install

# Copy the rest of the application code
COPY ./server .

# Expose the port on which the NestJS app will run
EXPOSE 3000

# Start the NestJS application
CMD ["npm", "run", "start:dev"]
