version: '1'

services:
  nest-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  angular-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    depends_on:
      - nest-backend
    volumes:
      - .:/app
