FROM node:18-alpine as builder

# Set the working directory
WORKDIR /app

COPY ./client ./

RUN npm install

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
